apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: {{ .Values.ingress.certManagerIssuer | default "axis-dns-issuer" }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.domain | replace "https://" "" }}