apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: evolution-api-route
  namespace: automation
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`whatsapp.armandogil.es`)
      kind: Rule
      services:
        - name: evolution-api-service
          port: 8080
  tls:
    secretName: whatsapp-tls-cert
    
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whatsapp-tls-cert
  namespace: automation
spec:
  secretName: whatsapp-tls-cert
  issuerRef:
    name: axis-dns-issuer
    kind: ClusterIssuer
  dnsNames:
    - whatsapp.armandogil.es