{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.ingress.host }}`) || Host(`www.{{ .Values.ingress.host }}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-wp
      port: 80
  tls:
    secretName: {{ .Values.ingress.tlsSecretName }}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.host }}-tls-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.ingress.host }}-tls-cert
  issuerRef:
    name: axis-dns-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}
    - www.{{ .Values.ingress.host }}

{{- end }}