apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: 
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" | quote }}  
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.wpSize }}