apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Estos valores deben venir codificados en base64 si se pasan por values.yaml
  # O ser sobreescritos por un SealedSecret con el mismo nombre.
  mysql-password: {{ .Values.database.password | b64enc | quote }}
  mysql-root-password: {{ .Values.database.rootPassword | b64enc | quote }}