apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wp
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wp
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.image.wordpress }}
        env:
        - name: WORDPRESS_DB_HOST
          # Corregido: El servicio se llama como el recurso MariaDB
          value: {{ .Values.database.host | default (printf "%s-db" .Release.Name) | quote }}
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.database.name | quote }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.database.user | quote }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              # Usamos la variable de la App de ArgoCD para ser flexibles
              name: {{ .Values.database.existingSecret | default (printf "%s-secrets" .Release.Name) | quote }}
              key: {{ .Values.database.passwordKey | default "mysql-password" | quote }}
        - name: WORDPRESS_TABLE_PREFIX
          value: {{ .Values.database.tablePrefix | default "wp_" | quote }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wp-data
          mountPath: /var/www/html
      volumes:
      - name: wp-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-wp-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wp
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-wp
  type: ClusterIP