namespace: default
replicaCount: 1

image:
  wordpress: wordpress:latest
  mariadb: mariadb:10.11
  pullPolicy: IfNotPresent

database:
  name: wordpress
  user: admin

persistence:
  storageClass: longhorn
  wpSize: 10Gi
  dbSize: 5Gi

ingress:
  enabled: true
  host: example.com
  tlsSecretName: wordpress-tls
  certManagerIssuer: axis-dns-issuer

# --- CONFIGURACIÓN GLOBAL DE BACKUPS AXIS ---
backup:
  enabled: true
  plan: "silver"          # Opciones: silver, gold, platinum
  region: "eu-west-1"
  s3Endpoint: "s3.eu-west-1.amazonaws.com"
  
  # Buckets reales de AWS S3
  bucketFull: "axis-mariadb-backup-789ddgum3nz4cz645bgo"
  bucketExports: "axis-mariadb-exports-2jjj4f3i07p7kme6idd2"
  
  # Horarios y Retención
  schedule: "*/30 * * * *"       # Cada 30 min para aprovechar incrementales
  maxRetention: "30d"            # Tiempo total de vida del backup en S3
  fullBackupIntervalHours: 24    # Un Full nuevo cada día