namespace: default
replicaCount: 1

image:
  wordpress: wordpress:latest
  mariadb: mariadb:10.11
  pullPolicy: IfNotPresent

database:
  name: wordpress
  user: admin

persistence:
  storageClass: longhorn
  wpSize: 10Gi
  dbSize: 5Gi

ingress:
  enabled: true
  host: example.com
  tlsSecretName: wordpress-tls
  certManagerIssuer: axis-dns-issuer

backup:
  enabled: true
  s3Endpoint: "s3.eu-west-1.amazonaws.com"
  bucket: "axis-backups"
  region: "eu-west-1"
  schedule: "0 3 * * *"
  maxRetention: "30d"
  pitr:
    enabled: false
    # Si quieres un bucket diferente para logs, lo definimos aqu√≠
    retention: "7d"