client_name: "client_name"
domain: "client_name.armandogil.es"

image:
  repository: odoo
  tag: "18.0"

db:
  user: "odoo_user"
  database: "odoo"
  secretName: "odoo-db-pass" # El que sellaremos con kubeseal
  size: "10Gi"

resources:
  limits:
    memory: "2Gi"
  requests:
    memory: "1Gi"

backup:
  enabled: true
  plan: "silver"          # Opciones: silver, gold, platinum

  storagelocation: "clients"
  
  schedule: "0 */4 * * *"       # Cada 30 min para aprovechar incrementales
  retention: "720h0m0s"         # Tiempo de vida del backup individual
  includeFiles: true            # Incluir wp-content en el backup

odoo:
  adminPasswordSecretName: "odoo-admin-password"

#responseTimeout: "30s"