client_name: "mercecastane"
namespace: client-mercecastane
domain: "odoo.mercecastane.es" # Ajusta a su subdominio real

image:
  repository: odoo
  tag: "18.0"

db:
  user: "odoo_mercecastane"
  secretName: "odoo-db-pass" # Este es el nombre que debe tener el SealedSecret
  size: "5Gi" # Un poco m√°s de espacio para Merce

persistence:
  size: "5Gi" # Espacio para el filestore (fotos, PDFs, facturas)
  storageClass: "longhorn"

resources:
  limits:
    memory: "2Gi"
  requests:
    memory: "1Gi"

backup:
  enabled: true
  plan: "silver"          # Opciones: silver, gold, platinum

  storagelocation: "clients"
  
  schedule: "0 */4 * * *"       # Cada 30 min para aprovechar incrementales
  retention: "720h0m0s"         # Tiempo de vida del backup individual
  includeFiles: true 