apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-html
  namespace: armandogil-landing
  annotations:
    # Must be created BEFORE the deployment (Wave 5)
    argocd.argoproj.io/sync-wave: "1"
data:
  index.html: |
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//ES"
"http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
        <head>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <meta name="Title" content="Armando Gil Bonet">
                <title>Armando Gil Bonet</title>
                <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates" rel="stylesheet">
        </head>
        <body style="font-family: 'Montserrat Alternates', sans-serif;">
                <div style="position: absolute;left: 50%;top: 50%;transform: translate(-50%, -50%);-webkit-transform: translate(-50%, -50%);">
                <h1 style="font-size:100px;font-weight:800;text-align:center;margin: 0 0 50px 0;">hola.</h1>
                </div>
        </body>
</html>
