apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
  - port: 19132
    targetPort: 19132
    nodePort: 31221 # Puerto fijo en el nodo (rango 30000-32767)
    protocol: UDP
    name: mc-bedrock
  selector:
    app: minecraft-bedrock