apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-ingressroute
  namespace: automation
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.armandogil.es`)
      kind: Rule
      services:
        - name: n8n-service
          port: 5678
  tls:
    secretName: n8n-tls-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls-cert
  namespace: automation
spec:
  secretName: n8n-tls-cert
  issuerRef:
    name: axis-dns-issuer
    kind: ClusterIssuer
  dnsNames:
    - n8n.armandogil.es