domain: "vault.armandogil.es"
signupsAllowed: "false"
databaseUrl: "data/vaultwarden.db"

persistence:
  storageClass: "longhorn"
  size: 2Gi

ingress:
  enabled: true
  host: "vault.armandogil.es"
  tlsSecretName: "vaultwarden-tls"
  certManagerIssuer: "axis-dns-issuer"