apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: client-{{ .Values.client_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 100:101 /var/lib/odoo"]
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
      containers:
      - name: odoo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh", "-c"]
        args:
          - |
            cp /etc/odoo/odoo.conf /tmp/odoo.conf && \
            echo "admin_passwd = $ADMIN_PASSWORD" >> /tmp/odoo.conf && \
            echo "db_password = $DB_PASSWORD" >> /tmp/odoo.conf && \
            echo "Infraestructura Axis lista. Arrancando..." && \
            exec odoo --config=/tmp/odoo.conf -d $DATABASE -i base
        ports:
        - containerPort: 8069
          name: web
        - containerPort: 8072
          name: chat
        env:
        - name: ADMIN_PASSWORD # Odoo mapea esto a admin_passwd internamente
          valueFrom:
            secretKeyRef:
              name: odoo-admin-password
              key: admin-password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-db-pass
              key: password
        - name: HOST
          value: "{{ .Release.Name }}-db-rw" # Host autom√°tico de CNPG
        - name: DATABASE
          value: {{ .Values.db.database | default "odoo" }}
        - name: USER
          value: {{ .Values.db.user | quote }}
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretName }}
              key: password
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.odoo.adminPasswordSecretName }}
              key: admin-password
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
        - name: odoo-config
          mountPath: /etc/odoo/odoo.conf
          subPath: odoo.conf
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-data
      - name: odoo-config
        configMap:
          name: {{ .Release.Name }}-config