apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: client-{{ .Values.client_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 100:101 /var/lib/odoo"]
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
      containers:
      - name: odoo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
          - "--db_host=$(HOST)"
          - "--db_user=$(USER)"
          - "--db_password=$(PASSWORD)"
          - "--db_name=odoo"  # Aquí sí le decimos que use 'odoo'
          - "--init=base"     # Si no existe la DB o el módulo, lo inicializa
          - "--proxy-mode"
        ports:
        - containerPort: 8069
          name: web
        - containerPort: 8072
          name: chat
        env:
        - name: HOST
          value: "{{ .Release.Name }}-db-rw" # Host automático de CNPG
        - name: USER
          value: {{ .Values.db.user | quote }}
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretName }}
              key: password
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-data