apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-db
  namespace: client-{{ .Values.client_name }}
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  
  storage:
    size: {{ .Values.db.size | default "10Gi" }}
    storageClass: {{ .Values.persistence.storageClass | default "longhorn" }}

  bootstrap:
    initdb:
      # Usamos 'postgres' para que CNPG no cree la DB 'odoo'
      # Pero asignamos al usuario de Odoo como owner de la instancia inicial
      database: {{ .Values.db.database | default "odoo" }}
      owner: {{ .Values.db.user | quote }}
      secret:
        name: {{ .Values.db.secretName }}
      postInitApplicationSQL:
        - ALTER USER {{ .Values.db.user }} WITH CREATEDB;

  # Gestión de backups integrada
  backup:
    barmanObjectStore:
      destinationPath: s3://axis-clients-backup-ukg2qr90zft4cbtmprmw/{{ .Values.client_name }}/odoo/
      endpointURL: https://s3.eu-west-1.amazonaws.com # Ajusta a tu S3
      data:
        compression: gzip
        jobs: 2
      wal:
        compression: gzip
      s3Credentials:
        accessKeyId:
          name: aws-s3-backups
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: aws-s3-backups
          key: AWS_SECRET_ACCESS_KEY
    retentionPolicy: "30d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Release.Name }}-daily-backup
spec:
  schedule: "0 0 3 * * *" # Todos los días a las 3 AM
  cluster:
    name: {{ .Release.Name }}-db