apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-data
  namespace: client-{{ .Values.client_name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass | default "longhorn" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}