apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-https
  namespace: client-{{ .Values.client_name }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    services:
    - name: {{ .Release.Name }}-service
      port: 8069
      #responseTimeout: {{ .Values.responseTimeout | default "30s" }}
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) && PathPrefix(`/websocket`)
    services:
      - name: {{ .Release.Name }}-service
        port: 8072
  tls:
    secretName: {{ .Values.client_name }}-odoo-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.client_name }}-odoo-cert
  namespace: client-{{ .Values.client_name }}
spec:
  secretName: {{ .Values.client_name }}-odoo-tls
  issuerRef:
    name: axis-dns-issuer
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.domain }}