apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: client-{{ .Values.client_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 100:101 /var/lib/odoo"]
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
      containers:
      - name: odoo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
          - "--config=/etc/odoo/odoo.conf"
          - "--admin-passwd=$(ADMIN_PASSWORD)" # Kubernetes expande esto antes de lanzar Odoo
          - "--db_password=$(PASSWORD)"
        ports:
        - containerPort: 8069
          name: web
        - containerPort: 8072
          name: chat
        env:
        - name: HOST
          value: "{{ .Release.Name }}-db-rw" # Host autom√°tico de CNPG
        - name: DATABASE
          value: {{ .Values.db.database | default "odoo" }}
        - name: USER
          value: {{ .Values.db.user | quote }}
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretName }}
              key: password
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.odoo.adminPasswordSecretName }}
              key: admin-password
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
        - name: odoo-config
          mountPath: /etc/odoo/odoo.conf
          subPath: odoo.conf
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-data
      - name: odoo-config
        configMap:
          name: {{ .Release.Name }}-config