apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-https
  namespace: client-{{ .Values.client_name }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    services:
    - name: {{ .Release.Name }}-service
      port: 8069
      #responseTimeout: {{ .Values.responseTimeout | default "30s" }}
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) && PathPrefix(`/websocket`)
    services:
      - name: {{ .Release.Name }}-service
        port: 8072
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) && PathPrefix(`/web/database`)
    middlewares:
      - name: block-db-manager
    services:
      - name: {{ .Release.Name }}-service
        port: 8069
  tls:
    secretName: {{ .Values.client_name }}-odoo-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.client_name }}-odoo-cert
  namespace: client-{{ .Values.client_name }}
spec:
  secretName: {{ .Values.client_name }}-odoo-tls
  issuerRef:
    name: axis-dns-issuer
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.domain }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: block-db-manager
  namespace: client-{{ .Values.client_name }}
spec:
  ipWhiteList:
    sourceRange:
      {{- if .Values.mgmt_ips }}
      {{- toYaml .Values.mgmt_ips | nindent 6 }}
      {{- else }}
      - 127.0.0.1/32  # Bloqueo total por defecto
      {{- end }}